-- =====================================================================
--  NEBULA Affiliés — schéma PostgreSQL (Supabase)
--  À exécuter UNE FOIS dans Supabase : SQL Editor → coller → Run.
--
--  Traduit depuis le SQLite d'origine (init_db + migrate de server.py).
--  Deux traductions comptent :
--    · INTEGER PRIMARY KEY AUTOINCREMENT → GENERATED BY DEFAULT AS IDENTITY
--    · REAL → double precision
--      /!\ En SQLite, REAL fait 8 octets. En PostgreSQL, REAL n'en fait que 4,
--          ce qui ARRONDIT un horodatage Unix (1,7 milliard) et décale les dates
--          de plusieurs minutes. Toutes les dates de cette base sont des
--          horodatages Unix : elles doivent être en double precision.
--
--  Tout vit dans le schéma « naff », pour ne pas se mêler aux tables de
--  Boussole qui partagent le même projet Supabase. L'application pose
--  search_path = naff, donc AUCUNE requête n'a besoin d'être préfixée.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS naff;
SET search_path TO naff, public;

-- ---------- les partenaires ----------
CREATE TABLE IF NOT EXISTS affiliates(
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                 text UNIQUE NOT NULL,
  nom                  text,
  prenom               text,
  momo_number          text,
  momo_reseau          text,
  pin                  text NOT NULL,
  accent               text DEFAULT '#7b5cff',
  actif                integer DEFAULT 1,
  created              double precision,
  pseudo               text DEFAULT '',
  parrain_id           integer DEFAULT 0,
  photo                text DEFAULT '',
  direct_rate_override double precision DEFAULT 0,
  email                text DEFAULT '',
  tg_chat              text DEFAULT '',
  tg_token             text DEFAULT '',
  role                 text DEFAULT ''
);

-- ---------- les clients apportés ----------
CREATE TABLE IF NOT EXISTS leads(
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  affiliate_id integer NOT NULL,
  nom          text, prenom text, numero text,
  service      text, message text,
  status       text DEFAULT 'attente',
  paye         integer DEFAULT 0,
  montant      double precision DEFAULT 0,
  created      double precision,
  updated      double precision,
  source       text DEFAULT 'affilie',
  service_raw  text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS history(
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id    integer NOT NULL,
  old_status text, new_status text, note text,
  at         double precision
);

CREATE TABLE IF NOT EXISTS notifs(
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_role text NOT NULL,          -- 'admin' | 'affiliate'
  target_id   integer DEFAULT 0,      -- id affilié (0 = admin global)
  lead_id     integer,
  text        text,
  lu          integer DEFAULT 0,
  created     double precision,
  kind        text DEFAULT 'info',
  ref_aff     integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS brain_msgs(
  id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope    text NOT NULL,             -- 'admin' | 'aff'
  scope_id integer DEFAULT 0,
  who      text,                      -- 'user' | 'nova'
  text     text,
  created  double precision
);

CREATE TABLE IF NOT EXISTS agency_chats(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip text, question text, answer text,
  created double precision
);

-- ---------- le recrutement ----------
CREATE TABLE IF NOT EXISTS recruits(
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parrain_id  integer NOT NULL,
  nom text, prenom text, numero text,
  momo_number text, momo_reseau text, message text,
  status      text DEFAULT 'pending', -- 'pending' | 'approved' | 'rejected'
  created     double precision,
  email       text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS candidatures(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom text, prenom text, email text, numero text, ville text,
  momo_number text, momo_reseau text,
  experience text, motivation text, canaux text,
  parrain_code  text DEFAULT '',
  terms_version text,
  accepted_at   double precision,
  ip     text,
  status text DEFAULT 'pending',
  created double precision
);

-- ---------- l'argent ----------
CREATE TABLE IF NOT EXISTS commissions(
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id        integer NOT NULL,
  beneficiary_id integer NOT NULL,
  level          text,                -- 'direct' | 'n1' | 'n2'
  amount         double precision,
  status         text DEFAULT 'due',  -- 'due' | 'claimed' | 'paid' | 'void'
  created        double precision,
  claimed_at     double precision,
  paid_at        double precision
);

CREATE TABLE IF NOT EXISTS subscriptions(
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id        integer NOT NULL,
  affiliate_id   integer NOT NULL,
  offre          text,
  montant        double precision DEFAULT 20000,
  debut          double precision,
  echeance       double precision,
  statut         text DEFAULT 'actif',
  dernier_rappel double precision DEFAULT 0,
  relances       integer DEFAULT 0,
  created        double precision,
  updated        double precision
);

-- ---------- documentation et publications ----------
CREATE TABLE IF NOT EXISTS documents(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text, category text, description text,
  kind     text DEFAULT 'note',       -- 'note' | 'pdf' | 'link'
  body     text DEFAULT '',
  url      text DEFAULT '',
  filename text DEFAULT '',
  size     integer DEFAULT 0,
  updated  double precision,
  created  double precision
);

CREATE TABLE IF NOT EXISTS publications(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  ptype      text DEFAULT 'post',
  body       text DEFAULT '',
  script     text DEFAULT '',
  platforms  text DEFAULT '',
  media_kind text DEFAULT 'none',
  media_url  text DEFAULT '',
  filename   text DEFAULT '',
  updated double precision,
  created double precision
);

-- ---------- messagerie ----------
CREATE TABLE IF NOT EXISTS messages(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope      text,                    -- 'general' | 'dm'
  pair       text DEFAULT '',         -- pour 'dm' : 'uidA|uidB' trié
  sender_uid text,
  text       text,
  created    double precision
);

CREATE TABLE IF NOT EXISTS chat_reads(
  uid text, channel text,
  last_read double precision,
  PRIMARY KEY(uid, channel)
);

-- ---------- divers ----------
CREATE TABLE IF NOT EXISTS app_settings(
  k text PRIMARY KEY,
  v text
);

CREATE TABLE IF NOT EXISTS link_events(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  affiliate_id integer,
  kind text,                          -- 'open' | 'client' | 'partner'
  created double precision
);

-- ---------- index sur les colonnes réellement filtrées ----------
CREATE INDEX IF NOT EXISTS idx_leads_aff        ON leads(affiliate_id);
CREATE INDEX IF NOT EXISTS idx_leads_status     ON leads(status);
CREATE INDEX IF NOT EXISTS idx_comm_benef       ON commissions(beneficiary_id);
CREATE INDEX IF NOT EXISTS idx_comm_lead        ON commissions(lead_id);
CREATE INDEX IF NOT EXISTS idx_notifs_cible     ON notifs(target_role, target_id, lu);
CREATE INDEX IF NOT EXISTS idx_subs_echeance    ON subscriptions(echeance);
CREATE INDEX IF NOT EXISTS idx_msg_pair         ON messages(pair);
CREATE INDEX IF NOT EXISTS idx_aff_parrain      ON affiliates(parrain_id);
CREATE INDEX IF NOT EXISTS idx_history_lead     ON history(lead_id);

-- =====================================================================
--  Sécurité : ces tables ne sont JAMAIS lues depuis un navigateur.
--  L'application se connecte en Postgres direct avec le mot de passe de
--  la base, jamais avec la clé « anon » publique. On active donc RLS
--  sans aucune policy : personne ne passe par l'API REST de Supabase,
--  et le rôle de connexion de l'application n'est pas soumis à RLS.
-- =====================================================================
ALTER TABLE affiliates    ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads         ENABLE ROW LEVEL SECURITY;
ALTER TABLE history       ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifs        ENABLE ROW LEVEL SECURITY;
ALTER TABLE brain_msgs    ENABLE ROW LEVEL SECURITY;
ALTER TABLE agency_chats  ENABLE ROW LEVEL SECURITY;
ALTER TABLE recruits      ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidatures  ENABLE ROW LEVEL SECURITY;
ALTER TABLE commissions   ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents     ENABLE ROW LEVEL SECURITY;
ALTER TABLE publications  ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages      ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_reads    ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings  ENABLE ROW LEVEL SECURITY;
ALTER TABLE link_events   ENABLE ROW LEVEL SECURITY;
